stages:
  - testing

unit-test-job::
  stage: testing
  image: python:3.8-slim
  tags:
    - testing
    - test
  before_script:
    - apt-get update
    - apt-get install ffmpeg libsm6 libxext6  -y
    - python --version  # For debugging
    - pip3 install -r requirements.txt
  script:
    - pylint src
    - flake8 src --statistics --count
    - pytest
  only:
    - merge_requests